// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZtt_Yv7x-KstY9YHgJuAPpPjdzwAAmOI',
    appId: '1:117338045502:web:33fb7620b6492aab90e56f',
    messagingSenderId: '117338045502',
    projectId: 'chatapptute-8d612',
    authDomain: 'chatapptute-8d612.firebaseapp.com',
    storageBucket: 'chatapptute-8d612.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnawJAD62tqd3bCZNAkhOMQjEGpmdWCAU',
    appId: '1:117338045502:android:bd40d0fa9757e20c90e56f',
    messagingSenderId: '117338045502',
    projectId: 'chatapptute-8d612',
    storageBucket: 'chatapptute-8d612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHeo6rqO4Kmyz-yvqqgPMn17rx9x7-d08',
    appId: '1:117338045502:ios:a4062afbc3d01fd990e56f',
    messagingSenderId: '117338045502',
    projectId: 'chatapptute-8d612',
    storageBucket: 'chatapptute-8d612.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHeo6rqO4Kmyz-yvqqgPMn17rx9x7-d08',
    appId: '1:117338045502:ios:8da8ad301c497fa790e56f',
    messagingSenderId: '117338045502',
    projectId: 'chatapptute-8d612',
    storageBucket: 'chatapptute-8d612.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
